### ISSUE TITLE
Add Emoji

### ISSUE THREAD

**Issue by Harshu467** [SamarthKadam/ChatBox#14] opened 2024-05-10 12:06 UTC
Add Emoji Section

**Comment by Harshu467** [comment] 2024-05-10 12:06
My self Harsh Upadhye , I have participated in GSOC 23 last year, I have good experience of working on open source projects. Please Assign this to me

**Comment by abhiperfect** [comment] 2024-05-10 17:56
Subject: Bug Fix Request: Empty Message Sending 🐛

Hi,

I hope this message finds you well. I'm reaching out regarding a bug that I've encountered while working on our project.

Issue: When attempting to send a message, the system allows the user to send an empty message, resulting in unintended behavior.

**I have been working on a similar project, which you can find on my GitHub, so I believe I can offer valuable assistance in resolving this issue.**

Could you please assign this task to me so I can investigate and resolve the issue promptly? I'm confident I can provide insights and contribute effectively to fixing this bug.

Looking forward to your response.

Best regards,
Abhishek

**Comment by abhiperfect** [comment] 2024-05-10 18:17
Subject: Add emoji 
like this:
![Screenshot 2024-05-03 210522](https://github.com/SamarthKadam/ChatBox/assets/114478676/26c80cb1-19e8-426c-bb16-23c3e88d2b91)

Hi ,

I hope this message finds you well.

Issue: Adding emoji functionality.

I have been working on a similar project, which you can find on my GitHub, so I believe I can offer valuable assistance in resolving this issue.

Could you please assign this task to me so I can investigate and resolve the issue promptly? I'm confident I can provide insights and contribute effectively to fixing this bug.

Looking forward to your response.

Best regards,
Abhishek Prajapati

**Comment by abhiperfect** [comment] 2024-05-11 13:39
Hello, @SamarthKadam  , is there any demo account available so I can log into your application?

**Comment by SamarthKadam** [comment] 2024-05-11 16:19
@abhiperfect please try again and let me know

**Comment by Abhinav-Sharma06** [comment] 2024-05-11 16:30
Hi @SamarthKadam ,

I'm eager to take on this task. With my past experience with related issues, I'm sure I can handle it well. Please assign it to me. Thanks!

**Comment by abhiperfect** [comment] 2024-05-11 16:30
> @abhiperfect please try again and let me know
Still same issue:
![Screenshot 2024-05-11 215843](https://github.com/SamarthKadam/ChatBox/assets/114478676/c6f0587a-82dc-411f-9967-23d1618baf26)

**Closed** 2024-05-16 16:49 UTC
Labels: gssoc, level2
